name: Deploy and Configure Development ENV

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ANSIBLE_HOST_KEY_CHECKING: False

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: AWS_REGION
          role-to-assume: OIDC_ROLE_ARN

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Generate Ansible Inventory
        run: |
          cd terraform
          terraform output -json > tf_output.json
          cd ..
          ./scripts/generate_inventory.sh

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run GitLab Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/gitlab.yml

      # Optional pause or wait for token injection if needed
      - name: Wait for Token (Optional)
        run: echo "Insert registration_token manually into group_vars/runners.yml"

      - name: Run Runners Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/runners.yml

      - name: Run Harbor Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory/hosts.ini playbooks/harbor.yml
